### PR TITLE
Use query parameters to transmit form values where the form is submitted via GET

### PR DESCRIPTION
**Pull request by mpscholten**

### CODE REVIEW

**Comment by CSchank** [comment]
Ouuu actually, I think I want to use this in the pagination filtering (which I'm about ready to submit as a WIP PR). Right now it's kind of a confusing hybrid where the text box submits as a POST request but then the page numbers along the bottom have to manually put it in as a GET when the user wants to change pages. If instead it was always in the URL from the start that would make more sense.

**Comment by mpscholten** [comment]
Good point, the initial problem reported via gitter was basically a similiar problem (search query input field)

**Comment by CSchank** [comment]
Great, now that this is merged I will update my PR against the new version.

**Comment by philschonholzer** [comment]
Thanks @mpscholten! I tested this change as you described, by placing this `helper.js` in the static folder. Now my search query behaves just as I want it to.

**Pull request merged**
