### PR TITLE
Add mocking framework for controllers

### PR DESCRIPTION
**Pull request by nghamilton**
Is this useful to incorporate into IHP framework? Is this the right spot for it?

Example usage:
```
import Test.Controller.Mocking

spec :: Spec
spec = beforeAll (configBuilder >>= mockContext >>= \c -> withContext c (pure ()) do
  describe "Run mock test" do

    it "checks headers" $ c -> withParams [("param","val"] c do
      heads <- headers (mockAction SomeAction)
      let loc = lookup "Location" heads
      loc `shouldNotBe` Nothing

    it "checks status" $ c -> withParams [("param","val"] c do
      mockActionStatus AnotherAction `shouldReturn` status200
```

### CODE REVIEW

**Comment by mpscholten** [comment]
Yes, let's add this to IHP :) If we want this to be callable from userland we should propably name the module something like `IHP.Test.Controller`. We should also add some documentation on this to the Guide.

**Comment by nghamilton** [comment]
Cool, I can do that.

Is there a neat way to get rid of the userland dependencies? `WebApplication`, `User`, and the `RootApplication` instance of `FrontController`? I reckon they need to be taken out.

**Comment by mpscholten** [comment]
The `RootApplication` can stay as it's defined in the `IHP.FrameworkConfig` module. We could pass the `WebApplication` as an argument to `withContext`. This would also help to solve the `User` issue, as we could now just call the `initContext` of the `InitControllerContext WebApplication` instance (like https://github.com/digitallyinduced/ihp-blog-example-app/blob/master/Web/FrontController.hs#L20). That `initContext` would then set the user to `Nothing`. If a specific test case needs a custom user, it could always call `putContext` to override the `Nothing` value with a mock user.

**Comment by nghamilton** [comment]
I have tidied up the mocking context, if we are happy with it I'll write up some docs.

**Comment by mpscholten** [comment]
Looks good to me 👍

**Comment by nghamilton** [comment]
Updated and added docs.

**Review by mpscholten — APPROVED** [review]
Looks good, thanks 👍

**Pull request merged**
