### PR TITLE
Migration path Env Var.

### PR DESCRIPTION
**Pull request by Montmorency**
Adds an environment variable so user can run migration systemd service from any directory on FileSystem. Useful in certain production situations. Defaults to the previous value. Docs updated.

### CODE REVIEW

**Review by mpscholten — APPROVED** [review]
Looks good to me 👍

**Comment by mpscholten** [comment]
With this we can now simplify the migration service here https://github.com/digitallyinduced/ihp/blob/master/NixSupport/nixosModules/services/migrate.nix#L10 a little bit

**Comment by Montmorency** [comment]
> With this we can now simplify the migration service here https://github.com/digitallyinduced/ihp/blob/master/NixSupport/nixosModules/services/migrate.nix#L10 a little bit

Yes that line confuses me 😄 . What can it be switched to now?

**Comment by mpscholten** [comment]
simplified version is here https://github.com/digitallyinduced/ihp/pull/2016/files

**Pull request merged**
