### PR TITLE
Delay app start until postgres is ready. Fixes #1210

### LINKED ISSUE #1210: libpq errors on Gitpod
When spinning a new instance on Gitpod it's easy to come across these two errors:

image

image

## Steps

1. Open [this Gitpod](https://gitpod.io/#https://github.com/Gizra/ihp-simple-seat-reservation)
2. As soon as port 8000 is available open it 
image

The error will go away after a few sec, but maybe there's a way to prevent this error and provide a nicer experience for people trying it out.

### PR DESCRIPTION
**Pull request by mpscholten**
@amitaibu can you give this a try? :)

### CODE REVIEW

**Comment by amitaibu** [comment]
Sure, checking ...

**Comment by amitaibu** [comment]
I'm trying this on https://github.com/Gizra/ihp-simple-seat-reservation/pull/6 - and I think it works well (trying to run another instance to confirm).

However, it now takes ~30 min to compile where as before it took less than 1 min. Has something changed?
To reproduce you can click on the Gitpod badge on my PR

**Comment by amitaibu** [comment]
(To compare to a quicker version, click on the Badge in https://github.com/Gizra/ihp-simple-seat-reservation#readme)

**Comment by mpscholten** [comment]
Ah yes, the `ref = "app-delayed-start-until-db-ready";` is breaking caching of nix and then it triggers a full build of IHP on gitpod. try `rev = "<the commit hash">`, that should hit the cachix binary cache and avoid a full rebuild.

**Comment by amitaibu** [comment]
Yeah, I've added the `rev` along with `ref` otherwise it didn't recognize it.

However, I'm still seeing:

image

**Comment by amitaibu** [comment]
Also, I think line breaks are broken in the logs

image

**Comment by mpscholten** [comment]
Fixed the logs via https://github.com/digitallyinduced/ihp/commit/c8dc8d0e5d1fe1ac52b115b99f5cf36694100c1e

**Pull request merged**
