### PR TITLE
WIP: Use steeloverseer to add debounce

### PR DESCRIPTION
**Pull request by amitaibu**
A very naive start with the help of ChatGPT for https://github.com/digitallyinduced/ihp/issues/1809

How can I add [this](https://search.nixos.org/packages?channel=23.11&show=haskellPackages.steeloverseer&from=0&size=50&sort=relevance&type=packages&query=steeloverseer) nix package to IHP?

image

### CODE REVIEW

**Comment by amitaibu** [comment]
I think I was able to get the package installed, I missed another place.

Next I need to follow https://github.com/digitallyinduced/ihp/blob/master/CONTRIBUTING.md#running-the-development-server

**Comment by amitaibu** [comment]
@mpscholten is the explanation [here](https://github.com/digitallyinduced/ihp/blob/master/CONTRIBUTING.md#running-the-development-server) correct?

| Command | output |
| - | - |
| `:l IHP/exe/IHP/IDE/DevServer.hs` | image |
| `main` | image |

**Comment by amitaibu** [comment]
Sorry, I should have scrolled more up, and see the error related to my code

image

**Comment by amitaibu** [comment]
Do I need to define the lib in another place?

**Comment by mpscholten** [comment]
It looks like steeloverseer only re-exports the "old" debounce system from FSNotify https://github.com/schell/steeloverseer/blob/master/src/System/FSNotify/Streaming.hs#L19 

So this approach won't work

**Comment by amitaibu** [comment]
Closed in favor of https://github.com/digitallyinduced/ihp/pull/1882

**Pull request closed without merging**
