### PR TITLE
Use a nixpkgs revision where apple m1 is supported

### PR DESCRIPTION
**Pull request by mpscholten**
This PR adds support for Apple M1 macs.

Follow https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-a-specific-git-commit to update to this branch.

[This nixpkgs revision has working binaries for M1 on hydra, so it should definitly work this time.](https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/ghc.aarch64-darwin)

If you're a M1 user, please let me know if this is working.

### CODE REVIEW

**Comment by rottabonus** [comment]
Hi, I tried using the this PR's commit with provided instructions, but I get following to my terminal after running <strong>nix-shell -j auto --cores 0 --run 'make -B .envrc </strong>

```console
error: invalid Git branch/tag name '*'
```

Here is my default.nix changed config:
```haskell
let
       ihp = builtins.fetchGit {
           url = "https://github.com/digitallyinduced/ihp.git";
           rev = "bc930af2318afd3823bbbb88cf5605a013b81d08";
           ref = "*";
       };
```

Is there something obvious I'm missing? Thanks!

**Comment by mpscholten** [comment]
I think this has changed with recent nix version. Try this without `ref = *`:

```nix
let
       ihp = builtins.fetchGit {
           url = "https://github.com/digitallyinduced/ihp.git";
           rev = "bc930af2318afd3823bbbb88cf5605a013b81d08";
       };
```

Btw: This branch sadly doesn't natively work on M1 yet. We tested it but didn't get it to work. So likely this will not get you further :)

**Comment by rottabonus** [comment]
Thanks for the reply.

 I'll keep my eyes open for the future then.

When IHP runs natively on Apple silicon I'll be glad to hop on board.

**Comment by mpscholten** [comment]
IHP now works on M1 with the latest release 👍

**Pull request closed without merging**
