### PR TITLE
use qualified nixpkgs attribute paths to avoid large evaluations

### PR DESCRIPTION
**Pull request by chrislf**
This is to address https://github.com/digitallyinduced/ihp/issues/265

### CODE REVIEW

**Comment by mpscholten** [comment]
Hey Chris, thanks for the PR 👍 We've tried to similiar changes to the docs a while ago and then found out that `nix-env -iA nixpkgs....` fails on NixOS systems. I just tried it out again on one of our NixOS systems and got the following error:

```bash
[root@haskell:~]# nix-env -iA nixpkgs.cachix
error: attribute 'nixpkgs' in selection path 'nixpkgs.cachix' not found
```

When using `nixos.cachix` instead of `nixpkgs.cachix`, this works:
```bash
[root@haskell:~]# nix-env -iA nixos.cachix
installing 'cachix-0.3.0'
```

Maybe we can have some variable `NIXPKGS_ATTR = if is_nixos then "nixos" else "nixpkgs"` and then use it like `nix-env -iA $NIXPKGS_ATTR.cachix`.

**Comment by chrislf** [comment]
Interesting, I didn't realise it was different on NixOS. I will install on a VM and test with your suggested approach.

**Comment by mpscholten** [comment]
Any updates? :)

**Comment by chrislf** [comment]
I got steamrollered this week: going to give this a shot this evening, however.

**Comment by chrislf** [comment]
I've tested these changes on NixOS (20.03 on VirtualBox), Amazon Linux and Ubuntu 18.04 and they seem to work fine.

For the CI changes, I didn't have a Mac to test the on but I understand the nixpkgs namespace works as for other non-NixOS OSes.

**Comment by mpscholten** [comment]
Looks great, thank you! 🙏

**Pull request merged**
