### PR TITLE
Issue 199/generators application aware

### LINKED ISSUE #199: Generators should be application-aware
Currently generators only work with the `Web` application. This should be selectable when there exist multilple apps.

### PR DESCRIPTION
**Pull request by Laobiz**
closes #199

### CODE REVIEW

**Comment by mpscholten** [comment]
Can we also add this to the controller generator?

**Comment by mpscholten** [comment]
Where is the application argument passed from the preview to the actual code generation? I could not find a hidden input for this, and it's also not an url query param

**Comment by Laobiz** [comment]
@mpscholten There is no argument that is passed. The path of the generated files is altered and so the plan which is displayed in the preview is another than the one with another application.

I will apply the Select Form to the controller generator as well :)

**Comment by mpscholten** [comment]
But when clicking Generate (after looking at the preview), where is the application passed?

**Comment by Laobiz** [comment]
Oh yeah good point. There is a hidden field missing I think. Good catch 👍

**Comment by mpscholten** [comment]
Can we hide the application selector when there is only a single application? Because then it's basically just noise

**Comment by Laobiz** [comment]
Good point :)

Marc Scholten <notifications@github.com> schrieb am Di., 14. Juli 2020,
11:55:

**Pull request merged**
