### PR TITLE
Update testing.markdown - workaround GH Runner disk space issue

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Review by mpscholten — APPROVED** [review]

**Comment by amitaibu** [comment]
@mpscholten seems like tests are failing. Do you happen to know know why?

**Comment by mpscholten** [comment]
I've moved the hsx tests to the ihp-hsx package (previously the were part of the ihp package), but forgot to remove them from the `Test/Main.hs`. Will fix this in a minute :+1:

**Comment by amitaibu** [comment]
Thanks

**Comment by amitaibu** [comment]
I still have one concern: before you fixed it, the test on 'master' occasionally worked.

image

Maybe tests are not running as they should on `master`?

**Comment by mpscholten** [comment]
Good point. I've changed the github configuration via https://github.com/digitallyinduced/ihp/commit/6bba47921a27b61e1098cc01106f17fe01a3a4ad this likely fixes that 👍

**Pull request merged**
