### PR TITLE
Escape single quotes

### PR DESCRIPTION
**Pull request by k-bx**
Not 100% where `parseValues` is used, so this might be completely wrong.

Fixes https://github.com/digitallyinduced/ihp/issues/642 (partially)

### CODE REVIEW

**Comment by k-bx** [comment]
not sure that error is mine ^

**Comment by mpscholten** [comment]
I'd rather do this a little bit different and use the Postgresql Parameter Substitution.

There's this action constructor here: https://hackage.haskell.org/package/postgresql-simple-0.6.2/docs/Database-PostgreSQL-Simple-ToField.html

We could change `parseValues` to return a `Action` instead of text. The function then could look like this:

```haskell
parseValues :: Bool -> Bool -> Text -> Action
parseValues _ True "on" = toField True
parseValues _ True "off" = toField False
parseValues False _ text = toField text
parseValues _ _ text = Plain text
```

Then at all call-sites of the `parseValues` function we need to change the calls from `PG.execute_` to `PG.execute`. The `PG.execute` takes a list of parameters to substitute as a additional argument (the query should have a `?` for every parameter in the sql string).

So bascially it should look like this at the call site:
```haskell
let values :: [Action] = ...
let query = "INSERT INTO " <> tableName <> " VALUES (" <> map (const "?") values <> ")"
PG.execute connection (PG.Query . cs $! query) values
```

**Comment by k-bx** [comment]
Good point! Substitution params are definitely the way to go, I wasn't familiar enough with IHP codebase thus proposed a minimal change, but thanks to your comment it wasn't hard to re-do via the param substitution.

Should be good to go now!

p.s.: the other thing with validation and errors needs quite a bit of work and I don't know if I'll have time for that, maybe at some point in future :)

**Review by mpscholten — APPROVED** [review]
Perfect, thanks :)

**Pull request merged**
