### PR TITLE
Fix Issue 766

### PR DESCRIPTION
**Pull request by s0kil**
This test should pass once the bug in the router is fixed.

Fixes https://github.com/digitallyinduced/ihp/issues/766

### CODE REVIEW

**Comment by s0kil** [comment]
So the issue is that the router tries to first parse as UUID, and then Int, Text, etc.
Since we want a UUID value as Text, this creates a conflict. Instead of messing around with the router, will update the [DevServer to use UUID's instead of Text](https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/ToolServer/Types.hs#L72)

**Comment by s0kil** [comment]
Maybe it's possible to add an runtime error in the Typed AutoRouter instead of segfaulting?

**Comment by s0kil** [comment]
Tested, Should be good to go!

**Comment by s0kil** [comment]
@zacwood9 Maybe you could weight in on this?

**Comment by zacwood9** [comment]
That's a nasty bug. In general the auto router is all done in an `Either` type that tries to catch all the possible errors that take place, but things get weird with UUIDs.

```haskell
\case
                Just queryValue -> queryValue
                    |> fromASCIIBytes
                    |> \case
                        Just uuid -> uuid |> unsafeCoerce |> Right
                        Nothing -> Left NotMatched
                Nothing -> Left NotMatched,
```

This is different than all the other type checks, which explicitly try to cast to Int, Text, etc because the only use case I had considered was UUIDs wrapped in a polymorphic `Id` newtype, like `Id User`. There's no way I'm aware of to match on those types with `Data.Data`, so instead I just used the same way old AutoRoute handled it, which `unsafeCoerce`s the UUID into the `Id a`.

I don't remember off the top of my head but there's probably some way to safely coerce, which we could then check the result of and return a `Left NotMatched` if the type coercion failed.

**Comment by zacwood9** [comment]
Alternatively we could just try the UUID check last. Then the `Text` type match will trigger and the world will be saved. This is probably better anyway since from some light profiling I did `fromASCIIBytes` is a pretty expensive function, and now will be called for every route

**Comment by s0kil** [comment]
> Alternatively we could just try the UUID check last.

Similar solution that I came up with, so will give it a go.

**Comment by s0kil** [comment]
We could leave the `Data/Controller` types as `UUID`, instead of reverting to `Text`.

**Comment by mpscholten** [comment]
One more tricky case: The primary could also be a non UUID column (e.g. an integer or a string).

Here's some real world example:
```sql
CREATE TABLE continents (
    id CHARACTER(2) PRIMARY KEY NOT NULL,
    name CHARACTER VARYING(510) DEFAULT NULL
);
CREATE TABLE countries (
    id CHARACTER(2) PRIMARY KEY NOT NULL,
    name CHARACTER VARYING(128) NOT NULL,
    full_name CHARACTER VARYING(256),
    iso3 CHARACTER(3),
    iso_number INT,
    continent CHARACTER(2) NOT NULL,
    stripe_tax_rate_id TEXT DEFAULT NULL
);
```

So we might make this unsupported by switching it from text to UUID

**Review by mpscholten — APPROVED** [review]

**Pull request merged**
