### PR TITLE
Add empty option value to styledSelectFormField for required html validation

### PR DESCRIPTION
**Pull request by andreytroeglazov**

### CODE REVIEW

**Comment by amitaibu** [comment]
@andreytroeglazov Thanks. Errors seem unrelated. Can you please check if removing those imports fixes the issue

image

**Comment by andreytroeglazov** [comment]
If `required == True` we need `value=""` on placeholder so the html validation will work correctly.
If `required == False` it does not matter if we have `value=""` or not. But to keep things consistent I think it's better to always have `value=""` on placeholder option.

**Comment by mpscholten** [comment]
Thanks, got it now 👍

**Comment by mpscholten** [comment]
@andreytroeglazov the tests need to be updated as well https://github.com/digitallyinduced/ihp/actions/runs/10289623933/job/28477778824 can you take a look?

**Comment by andreytroeglazov** [comment]
@mpscholten sure, will check

**Pull request merged**
