### PR TITLE
Add filesystem example to recipes which can also be used to deliver a custom 404 page

### PR DESCRIPTION
**Pull request by zmijunkie**
Another (hopefully) helpfull recipe.

### CODE REVIEW

**Review by mpscholten — APPROVED** [review]
Thanks 👍 good job

**Comment by zmijunkie** [comment]
now I regret a bit I have not taken fetchOneOrNothing

**Comment by mpscholten** [comment]
You could do another PR to fix that :D

**Comment by zmijunkie** [comment]
;-)

**Pull request merged**
